# Tree search

## Code

In [20]:
import typing
import math
import collections
import dataclasses
import abc
import itertools

T = typing.TypeVar("T", int, float)
Vector = typing.Tuple[T, T]
VectorComponent = typing.List[T]
Vertex = typing.List[typing.Tuple[T, T]]

def check_axis_intersect(that: Vector, z: T):
    x, y = that
    return y >= z >= x


def is_collision(that: Vertex, other: VectorComponent) -> bool:
    if len(that) != len(other):
        raise ValueError("Invalid arguments, different length of values")

    return all([check_axis_intersect(t, z) for t, z in zip(that, other)])


@dataclasses.dataclass
class VectorNode:
    data: VectorComponent
    value: T

    def __gt__(self, other):
        return self.value > other.value

    def __str__(self):
        return f"{self.data}, {self.value}"

    def __iter__(self):
        return iter([*self.data, self.value])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, item):
        return self.vertex[item]

    def __setitem__(self, key, value):
        self.vertex[key] = value


def calc_distance(x: T, y: T):
    return math.fabs(y - x) / 2


def create_axis(_array: Vertex):
    all_data = []

    for arr in _array:
        d = calc_distance(*arr)

        all_data.append(((x, x + d), (x + d, y)))

    return all_data


def create_axis_node(arrays):
    return itertools.product(arrays)


@dataclasses.dataclass
class Node:
    vertex: Vertex
    nodes: list

    def append(self, node: VectorComponent):
        self.nodes.append(node)

    def is_collide(self, node: VectorComponent):
        return is_collision(self.vertex, node)

    def __len__(self):
        return len(self.nodes)

    def __iter__(self):
        return iter(self.nodes)

    def __hash__(self):
        _hash = hash(tuple(self.vertex))
        
        return _hash


@dataclasses.dataclass
class NodeValue:
    vertex: Vertex
    node: VectorNode

    def __gt__(self, other: VectorNode):
        return self.value > other.value

    @property
    def value(self):
        return self.node.value


class NodeContainerInterface(abc.ABC):
    @property
    @abc.abstractmethod
    def axis(self) -> Vertex: ...

    @property
    @abc.abstractmethod
    def children(self): ...

    @property
    @abc.abstractmethod
    def node(self) -> Node: ...

    @property
    @abc.abstractmethod
    def is_parent(self) -> bool: ...

    @abc.abstractmethod
    def insert(self, verx: VectorComponent): ...

    @abc.abstractmethod
    def sort(self): ...

    @abc.abstractmethod
    def __iter__(self): ...


class TreeNode:
    def __init__(self, axis: Vertex, limit_divisions=1):
        self.__children = {}
        self.__node = Node(vertex=axis, nodes=[])
        self.__axis = axis
        self.__limit_divisions = limit_divisions

    def __hash__(self):
        return hash(self.__node)
        
    @property
    def axis(self):
        return [*self.__axis]

    @property
    def children(self):
        return self.__children

    @property
    def node(self) -> Node:
        return self.__node

    @property
    def is_parent(self):
        return len(self.children) != 0

    def insert(self, verx: VectorComponent):
        return self._insert_recursive(verx)

    def sort(self):
        return self._get_iter_child_recursive()

    def __iter__(self):
        return iter(self._get_iter_child_recursive())
        
    def _insert_recursive(self, verx: VectorComponent):
        def create_vertex(verx):
            root_axis = collections.deque()
            
            for axis, c in zip(self.axis, verx):
                x, y = axis
                d = calc_distance(x, y)
                
                if  c >= x and c <= (x + d):
                    root_axis.append((x, x + d))
                else:
                    root_axis.append((x + d, y))

            axis = list(root_axis)

            return axis

        tree = TreeNode(create_vertex(verx), self.__limit_divisions - 1)
        tree_key = hash(tree)
    
        if tree_key in self.__children:
            tree = self.__children[tree_key]
        else:
            self.__children[tree_key] = tree
        
        if self.__limit_divisions > 0:
            return tree.insert(verx)
        else:
            if not tree.node.is_collide(verx):
                raise ValueError(f"Vertex no collide: {tree.node} {verx}")
            
            tree.node.append(verx)
        
        return tree

    def _get_iter_child_recursive(self):
        def get_iter_child(root, nodes=None):
            if nodes is None:
                nodes = []

            for _, child in root.children.items():
                node = child.node
                
                if child.is_parent:
                    get_iter_child(child, nodes)
                else:
                    if len(child.node) > 0:
                        nodes.append(child.node)

            return nodes

        return get_iter_child(self, [])

## Initialize and config data

In [ ]:
import sympy as sp
import numpy as np

N_COMPONENTS = 5000
LIMITS_RANGE = -3, 3

def generate_objective_function(n_dim, seed=None):
    if seed is not None:
        sp.random.seed(seed)
    
    syms = sp.symbols(f'x:{n_dim}')
    obj_func = 0
    
    for sym in syms:
        coef1 = sp.Rational(sp.randprime(1, 5), sp.randprime(1, 5))
        coef2 = sp.Rational(sp.randprime(1, 5), sp.randprime(1, 5))
        term = coef1 * sym**2 + coef2 * sp.sin(sym)

        obj_func += term
    
    return syms, obj_func


syms, eq = generate_objective_function(N_COMPONENTS)

OBJ_FUNC = sp.lambdify([syms], eq, modules='numpy')
ALL_SYMS = syms

## Execution

In [17]:
import collections
import itertools

import pandas as pd

def tree_search_algorithm(f, axis, n_it=10, n_p=5, n_limit=0):
    tree = TreeNode(axis)

    all_it = collections.deque()
    all_it_route = collections.deque()

    for it in range(n_it):
        local_min_point = collections.deque()

        for _ in range(n_p):
            data = [np.random.uniform(*_) for _ in tree.axis]
            value = f(data)

            tree.insert(VectorNode(data, value))

        for container in tree.sort():
            min_node = min(container)

            local_min_point.append(
                NodeValue(container.vertex, min_node)
            )

        if len(local_min_point) <= 0:
            continue

        local_min_node = min(local_min_point)

        all_it.append(list(min(local_min_point).node))
        all_it_route.append(local_min_node.vertex)

        tree = TreeNode(local_min_node.vertex, 2)

    return all_it, all_it_route


all_it, all_it_route = tree_search_algorithm(
    OBJ_FUNC, [(-3, 3) for _ in range(len(syms))], 10, 30, 2
)

In [18]:
pd.DataFrame(all_it_route)

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,"(1.5, 3)","(-1.5, 0.0)","(0.0, 1.5)","(1.5, 3)","(-1.5, 0.0)","(-3, -1.5)","(-3, -1.5)","(1.5, 3)","(-3, -1.5)","(1.5, 3)",...,"(0.0, 1.5)","(-1.5, 0.0)","(-3, -1.5)","(-3, -1.5)","(0.0, 1.5)","(1.5, 3)","(1.5, 3)","(0.0, 1.5)","(1.5, 3)","(1.5, 3)"
1,"(2.4375, 2.625)","(-0.5625, -0.375)","(0.5625, 0.75)","(2.0625, 2.25)","(-1.5, -1.3125)","(-2.625, -2.4375)","(-2.25, -2.0625)","(1.875, 2.0625)","(-1.875, -1.6875)","(1.875, 2.0625)",...,"(0.9375, 1.125)","(-1.5, -1.3125)","(-2.4375, -2.25)","(-2.0625, -1.875)","(1.125, 1.3125)","(2.625, 2.8125)","(2.8125, 3)","(0.75, 0.9375)","(1.875, 2.0625)","(1.875, 2.0625)"
2,"(2.578125, 2.6015625)","(-0.4453125, -0.421875)","(0.5625, 0.5859375)","(2.109375, 2.1328125)","(-1.40625, -1.3828125)","(-2.484375, -2.4609375)","(-2.0859375, -2.0625)","(1.9453125, 1.96875)","(-1.8046875, -1.78125)","(1.875, 1.8984375)",...,"(0.984375, 1.0078125)","(-1.453125, -1.4296875)","(-2.4140625, -2.390625)","(-2.015625, -1.9921875)","(1.2890625, 1.3125)","(2.6484375, 2.671875)","(2.953125, 2.9765625)","(0.84375, 0.8671875)","(1.96875, 1.9921875)","(1.921875, 1.9453125)"
3,"(2.58984375, 2.5927734375)","(-0.43359375, -0.4306640625)","(0.5771484375, 0.580078125)","(2.126953125, 2.1298828125)","(-1.4033203125, -1.400390625)","(-2.4638671875, -2.4609375)","(-2.0712890625, -2.068359375)","(1.951171875, 1.9541015625)","(-1.787109375, -1.7841796875)","(1.892578125, 1.8955078125)",...,"(0.990234375, 0.9931640625)","(-1.4501953125, -1.447265625)","(-2.4140625, -2.4111328125)","(-2.0009765625, -1.998046875)","(1.294921875, 1.2978515625)","(2.6630859375, 2.666015625)","(2.96484375, 2.9677734375)","(0.8525390625, 0.85546875)","(1.974609375, 1.9775390625)","(1.9423828125, 1.9453125)"
4,"(2.592041015625, 2.5924072265625)","(-0.432861328125, -0.4324951171875)","(0.5771484375, 0.5775146484375)","(2.12841796875, 2.1287841796875)","(-1.4022216796875, -1.40185546875)","(-2.46240234375, -2.4620361328125)","(-2.0701904296875, -2.06982421875)","(1.951904296875, 1.9522705078125)","(-1.7860107421875, -1.78564453125)","(1.8929443359375, 1.893310546875)",...,"(0.9913330078125, 0.99169921875)","(-1.44873046875, -1.4483642578125)","(-2.41259765625, -2.4122314453125)","(-1.9984130859375, -1.998046875)","(1.294921875, 1.2952880859375)","(2.6649169921875, 2.665283203125)","(2.9659423828125, 2.96630859375)","(0.85400390625, 0.8543701171875)","(1.9749755859375, 1.975341796875)","(1.944580078125, 1.9449462890625)"
5,"(2.5923614501953125, 2.5924072265625)","(-0.4325408935546875, -0.4324951171875)","(0.5771942138671875, 0.577239990234375)","(2.1287384033203125, 2.1287841796875)","(-1.4019012451171875, -1.40185546875)","(-2.462127685546875, -2.4620819091796875)","(-2.0698699951171875, -2.06982421875)","(1.951995849609375, 1.9520416259765625)","(-1.785736083984375, -1.7856903076171875)","(1.89312744140625, 1.8931732177734375)",...,"(0.991607666015625, 0.9916534423828125)","(-1.44854736328125, -1.4485015869140625)","(-2.4123687744140625, -2.412322998046875)","(-1.9980926513671875, -1.998046875)","(1.2950592041015625, 1.29510498046875)","(2.665191650390625, 2.6652374267578125)","(2.96612548828125, 2.9661712646484375)","(0.8541412353515625, 0.85418701171875)","(1.975067138671875, 1.9751129150390625)","(1.9448089599609375, 1.944854736328125)"
6,"(2.5924015045166016, 2.5924072265625)","(-0.43253517150878906, -0.4325294494628906)","(0.5772342681884766, 0.577239990234375)","(2.1287384033203125, 2.128744125366211)","(-1.4018611907958984, -1.40185546875)","(-2.462087631225586, -2.4620819091796875)","(-2.0698699951171875, -2.069864273071289)","(1.9520301818847656, 1.952035903930664)","(-1.7857017517089844, -1.785696029663086)","(1.8931388854980469, 1.8931446075439453)",...,"(0.9916248321533203, 0.9916305541992188)","(-1.4485244750976562, -1.4485187530517578)","(-2.412334442138672, -2.4123287200927734)","(-1.9980697631835938, -1.9980640411376953)","(1.2950878143310547, 1.2950935363769531)","(2.665203094482422, 2.6652088165283203)","(2.9661483764648438, 2.966154098510742)","(0.8541641235351562, 0.8541698455810547)","(1.9750957489013672, 1.9751014709472656)","(1.9448490142822266, 1.944854736328125)"
7,"(2.5924036502838135, 2.592404365539551)","(-0.43253517150878906, -0.43253445625305176)","(0.5772349834442139, 0.5772356986999512)","(2.1287426948547363, 2.1287434101104736)","(-1.4018604755401611, -1.4018597602844238)","(-2.4620869159698486, -2.4620862007141113)","(-2.0698649883270264, -2.069864273071289)","(1.9520344734191895, 1.9520351886749268)","(-1.7856981754302979, -1.7856974601745605)","(1.8931410312652588, 1.893141746520996)",...,"(0.9916262626647949, 0.9916269779205322)","(-1.4485201835632324, -1.4485194683074951)","(-2.412334442138672, -2.4123337268829346)","(-1.9980661869049072, -1.99806547164917)","(1.2950928211212158, 1.2950935363769531)","(2.6652066707611084, 2.6652073860168457)","(2.9661498069763184, 2.9661505222320557)","(0.8541641235351562, 0.8541648387908936)","(1.9750964641571045, 1.9750971794128418)","(1.9448497295379639, 1.9448504447937012)"
8,"(2.592404007911682, 2.5924040973186493)","(-0.4325345456600189, -0.43253445625305176)","(0.5772355198860168, 0.577235609292984)","(2.1287427842617035, 2.1287428736686707)","(-1.4018602967262268, -1.4018602073192596)","(-2.4620863795280457, -2.4620862901210785)","(-2.0698646306991577, -2.0698645412921906)","(1.9520344734191895, 1.9520345628261566)","(-1.7856980860233307, -1.7856979966163635)","(1.893141657114029, 1.893141746520996)",...,"(0.9916267991065979, 0.9916268885135651)","(-1.4485195577144623, -1.4485194683074951)","(-2.4123343527317047, -2.4123342633247375)","(-1.9980659186840057, -1.9980658292770386)","(1.2950930893421173, 1.2950931787490845)","(2.66520693898201, 2.665207028388977)","(2.96615007519722, 2.966150164604187)","(0.8541642129421234, 0.8541643023490906)","(1.9750965535640717, 1.9750966429710388)","(1.9448500871658325, 1.9448501765727997)"
9,"(2.5924040637910366, 2.5924040749669075)","(-0.43253448978066444, -0.43253447860479355)","(0.5772355422377586, 0.5772355534136295)","(2.128742828965187, 2.128742840141058)","(-1.4018602296710014, -1.4018602184951305)","(-2.462086346000433, -2.462086334824562)","(-2.0698645748198032, -2.0698645636439323)","(1.9520345516502857, 1.9520345628261566)","(-1.7856980301439762, -1.7856980189681053)","(1.8931416906416416, 1.8931417018175125)",...,"(0.9916268438100815, 0.9916268549859524)","(-1.448519490659237, -1.448519479483366)","(-2.4123342968523502, -2.4123342856764793)","(-1.9980658628046513, -1.9980658516287804)","(1.2950931005179882, 1.295093111693859)","(2.66520693898201, 2.665206950157881)","(2.9661501087248325, 2.9661501199007034)","(0.8541642241179943, 0.8541642352938652)","(1.9750965759158134, 1.9750965870916843)","(1.944850143045187, 1.944850154221058)"

In [19]:
pd.DataFrame(all_it)

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,500
0,2.220940,-1.224981,0.531505,2.442719,-0.012289,-2.421547,-2.236912,1.895389,-2.747803,1.657814,...,-0.939107,-1.500589,-2.007728,0.855395,2.164805,2.066441,0.853522,2.201003,2.931595,1363.884814
1,2.446254,-0.536260,0.743589,2.156395,-1.474844,-2.495005,-2.088026,2.036125,-1.824192,1.896802,...,-1.495548,-2.275988,-2.026853,1.183417,2.695348,2.852151,0.806360,2.052267,1.955704,1350.058601
2,2.599401,-0.443420,0.574594,2.127808,-1.400885,-2.483840,-2.078064,1.949138,-1.793524,1.894624,...,-1.439452,-2.411865,-1.994573,1.302930,2.669821,2.970221,0.851106,1.978688,1.939322,1339.821998
3,2.592306,-0.432312,0.578945,2.127144,-1.401407,-2.462194,-2.070755,1.952863,-1.785878,1.893786,...,-1.447852,-2.412458,-1.999884,1.296179,2.664450,2.967050,0.854919,1.977074,1.944670,1338.579074
4,2.592331,-0.432536,0.577471,2.128461,-1.402170,-2.462212,-2.070143,1.951933,-1.785913,1.893289,...,-1.448495,-2.412461,-1.998093,1.295225,2.665218,2.966220,0.854025,1.975091,1.944731,1338.358907
5,2.592380,-0.432532,0.577200,2.128766,-1.401899,-2.462084,-2.069850,1.952029,-1.785704,1.893156,...,-1.448504,-2.412334,-1.998060,1.295087,2.665233,2.966170,0.854185,1.975103,1.944842,1338.340543
6,2.592405,-0.432531,0.577236,2.128741,-1.401859,-2.462084,-2.069867,1.952033,-1.785699,1.893141,...,-1.448520,-2.412334,-1.998068,1.295089,2.665208,2.966149,0.854169,1.975099,1.944853,1338.339590
7,2.592404,-0.432535,0.577235,2.128743,-1.401860,-2.462087,-2.069865,1.952035,-1.785698,1.893141,...,-1.448520,-2.412334,-1.998066,1.295093,2.665207,2.966150,0.854164,1.975097,1.944850,1338.339463
8,2.592404,-0.432534,0.577236,2.128743,-1.401860,-2.462086,-2.069865,1.952035,-1.785698,1.893142,...,-1.448520,-2.412334,-1.998066,1.295093,2.665207,2.966150,0.854164,1.975097,1.944850,1338.339445
9,2.592404,-0.432534,0.577236,2.128743,-1.401860,-2.462086,-2.069865,1.952035,-1.785698,1.893142,...,-1.448519,-2.412334,-1.998066,1.295093,2.665207,2.966150,0.854164,1.975097,1.944850,1338.339442