# Tree search

## Code

In [22]:
import typing
import math
import collections
import dataclasses
import abc
import itertools

T = typing.TypeVar("T", int, float)
Vector = typing.Tuple[T, T]
VectorComponent = typing.List[T]
Vertex = typing.List[typing.Tuple[T, T]]

def check_axis_intersect(that: Vector, z: T):
    x, y = that
    return y >= z >= x


def is_collision(that: Vertex, other: VectorComponent) -> bool:
    if len(that) != len(other):
        raise ValueError("Invalid arguments, different length of values")

    return all([check_axis_intersect(t, z) for t, z in zip(that, other)])


@dataclasses.dataclass
class VectorNode:
    data: VectorComponent
    value: T

    def __gt__(self, other):
        return self.value > other.value

    def __str__(self):
        return f"{self.data}, {self.value}"

    def __iter__(self):
        return iter([*self.data, self.value])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, item):
        return self.vertex[item]

    def __setitem__(self, key, value):
        self.vertex[key] = value


def calc_distance(x: T, y: T):
    return math.fabs(y - x) / 2


def create_axis_node(arrays):
    return itertools.product(arrays)


@dataclasses.dataclass
class Node:
    vertex: Vertex
    nodes: list

    def append(self, node: VectorComponent):
        self.nodes.append(node)

    def is_collide(self, node: VectorComponent):
        return is_collision(self.vertex, node)

    def __len__(self):
        return len(self.nodes)

    def __iter__(self):
        return iter(self.nodes)

    def __hash__(self):
        _hash = hash(tuple(self.vertex))
        
        return _hash


@dataclasses.dataclass
class NodeValue:
    vertex: Vertex
    node: VectorNode

    def __gt__(self, other: VectorNode):
        return self.value > other.value

    @property
    def value(self):
        return self.node.value


class NodeContainerInterface(abc.ABC):
    @property
    @abc.abstractmethod
    def axis(self) -> Vertex: ...

    @property
    @abc.abstractmethod
    def children(self): ...

    @property
    @abc.abstractmethod
    def node(self) -> Node: ...

    @property
    @abc.abstractmethod
    def is_parent(self) -> bool: ...

    @abc.abstractmethod
    def insert(self, verx: VectorComponent): ...

    @abc.abstractmethod
    def sort(self): ...

    @abc.abstractmethod
    def __iter__(self): ...


class TreeNode:
    def __init__(self, axis: Vertex, limit_divisions=1):
        self.__children = {}
        self.__node = Node(vertex=axis, nodes=[])
        self.__axis = axis
        self.__limit_divisions = limit_divisions

    def __hash__(self):
        return hash(self.__node)
        
    @property
    def axis(self):
        return [*self.__axis]

    @property
    def children(self):
        return self.__children

    @property
    def node(self) -> Node:
        return self.__node

    @property
    def is_parent(self):
        return len(self.children) != 0

    def insert(self, verx: VectorComponent):
        return self._insert_recursive(verx)

    def sort(self):
        return self._get_iter_child_recursive()

    def __iter__(self):
        return iter(self._get_iter_child_recursive())
        
    def _insert_recursive(self, verx: VectorComponent):
        def create_vertex(verx):
            root_axis = collections.deque()
            
            for axis, c in zip(self.axis, verx):
                x, y = axis
                d = calc_distance(x, y)
                
                if  c >= x and c <= (x + d):
                    root_axis.append((x, x + d))
                else:
                    root_axis.append((x + d, y))

            axis = list(root_axis)

            return axis

        tree = TreeNode(create_vertex(verx), self.__limit_divisions - 1)
        tree_key = hash(tree)
    
        if tree_key in self.__children:
            tree = self.__children[tree_key]
        else:
            self.__children[tree_key] = tree
        
        if self.__limit_divisions > 0:
            return tree.insert(verx)
        else:
            if not tree.node.is_collide(verx):
                raise ValueError(f"Vertex no collide: {tree.node} {verx}")
            
            tree.node.append(verx)
        
        return tree

    def _get_iter_child_recursive(self):
        def get_iter_child(root, nodes=None):
            if nodes is None:
                nodes = []

            for _, child in root.children.items():
                node = child.node
                
                if child.is_parent:
                    get_iter_child(child, nodes)
                else:
                    if len(child.node) > 0:
                        nodes.append(child.node)

            return nodes

        return get_iter_child(self, [])

## Initialize and config data

In [23]:
import sympy as sp
import numpy as np

N_COMPONENTS = 1000000
LIMITS_RANGE = -3, 3

def generate_objective_function_rational(n_dim):    
    syms = sp.symbols(f'x:{n_dim}')
    obj_func = 0
    
    for sym in syms:
        coef1 = sp.Rational(sp.randprime(1, 5), sp.randprime(1, 5))
        coef2 = sp.Rational(sp.randprime(1, 5), sp.randprime(1, 5))
        term = coef1 * sym**2 + coef2 * sp.sin(sym)

        obj_func += term
    
    return syms, obj_func


def generate_objetive_function_add(n_dim):    
    syms = sp.symbols(f'x:{n_dim}')
    obj_func = 0
    
    for sym in syms:
        obj_func += sym
    
    return syms, obj_func


def generate_objetive_function_mul(n_dim):    
    syms = sp.symbols(f'x:{n_dim}')
    obj_func = 0
    
    for sym in syms:
        obj_func *= sym
    
    return syms, obj_func


def fobj_0(syms: list[float]) -> float:
    """
    sum from i=0 to n-1 of x_i
    
    :param syms: list[float]
    :return: float 
    """
    return sum(syms)


def fobj_1(syms: list[float]) -> float:
    """
    x_0 / ((sum from i=0 to n-2 of x_i) * x_(n-1))
    
    :param syms: list[float]
    :return: float 
    """
    return syms[0] / (sum(syms[0:-1]) * syms[-1])


def fobj_2(syms: list[float]) -> float:
    return syms[0] + ((sum(syms[0:-1]) ** 2) / syms[-1])


OBJ_FUNC = fobj_0

## Execution

In [ ]:
import collections
import itertools

import pandas as pd

def tree_search_algorithm(f, axis, n_it=10, n_p=5, n_limit=0):
    tree = TreeNode(axis)

    all_it = collections.deque()
    all_it_route = collections.deque()

    for it in range(n_it):
        local_min_point = collections.deque()

        for _ in range(n_p):
            data = [np.random.uniform(*i) for i in tree.axis]
            value = f(data)

            tree.insert(VectorNode(data, value))

        for container in tree.sort():
            min_node = min(container)

            local_min_point.append(
                NodeValue(container.vertex, min_node)
            )

        if len(local_min_point) <= 0:
            continue

        local_min_node = min(local_min_point)

        all_it.append(list(min(local_min_point).node))
        all_it_route.append(local_min_node.vertex)

        tree = TreeNode(local_min_node.vertex, 2)

    return all_it, all_it_route


all_it, all_it_route = tree_search_algorithm(
    OBJ_FUNC, [(-3, 3) for _ in range(N_COMPONENTS)], 10, 30, 2
)

In [20]:
pd.DataFrame(all_it_route)

                           0
0                 (-3, -1.5)
1              (-3, -2.8125)
2           (-3, -2.9765625)
3        (-3, -2.9970703125)
4     (-3, -2.9996337890625)
5  (-3, -2.9999542236328125)
6  (-3, -2.9999942779541016)
7  (-3, -2.9999992847442627)
8   (-3, -2.999999910593033)
9   (-3, -2.999999988824129)

In [21]:
pd.DataFrame(all_it)

          0         1
0 -2.445717 -2.445717
1 -2.993511 -2.993511
2 -2.997973 -2.997973
3 -2.999612 -2.999612
4 -2.999915 -2.999915
5 -2.999973 -2.999973
6 -2.999999 -2.999999
7 -3.000000 -3.000000
8 -3.000000 -3.000000
9 -3.000000 -3.000000