# Tree search

## Code

In [1]:
import typing
import math
import collections
import dataclasses
import abc
import itertools

T = typing.TypeVar("T", int, float)
Vector = typing.Tuple[T, T]
VectorComponent = typing.List[T]
Vertex = typing.List[typing.Tuple[T, T]]

def check_axis_intersect(that: Vector, z: T):
    x, y = that
    return y >= z >= x


def is_collision(that: Vertex, other: VectorComponent) -> bool:
    if len(that) != len(other):
        raise ValueError("Invalid arguments, different length of values")

    return all([check_axis_intersect(t, z) for t, z in zip(that, other)])


@dataclasses.dataclass
class VectorNode:
    data: VectorComponent
    value: T

    def __gt__(self, other):
        return self.value > other.value

    def __str__(self):
        return f"{self.data}, {self.value}"

    def __iter__(self):
        return iter([*self.data, self.value])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, item):
        return self.vertex[item]

    def __setitem__(self, key, value):
        self.vertex[key] = value


def calc_distance(x: T, y: T):
    return math.fabs(y - x) / 2


def create_axis(_array: Vertex):
    all_data = []

    for arr in _array:
        d = calc_distance(*arr)

        all_data.append(((x, x + d), (x + d, y)))

    return all_data


def create_axis_node(arrays):
    return itertools.product(arrays)


@dataclasses.dataclass
class Node:
    vertex: Vertex
    nodes: list

    def append(self, node: VectorComponent):
        self.nodes.append(node)

    def is_collide(self, node: VectorComponent):
        return is_collision(self.vertex, node)

    def __len__(self):
        return len(self.nodes)

    def __iter__(self):
        return iter(self.nodes)

    def __hash__(self):
        _hash = hash(tuple(self.vertex))
        
        return _hash


@dataclasses.dataclass
class NodeValue:
    vertex: Vertex
    node: VectorNode

    def __gt__(self, other: VectorNode):
        return self.value > other.value

    @property
    def value(self):
        return self.node.value


class NodeContainerInterface(abc.ABC):
    @property
    @abc.abstractmethod
    def axis(self) -> Vertex: ...

    @property
    @abc.abstractmethod
    def children(self): ...

    @property
    @abc.abstractmethod
    def node(self) -> Node: ...

    @property
    @abc.abstractmethod
    def is_parent(self) -> bool: ...

    @abc.abstractmethod
    def insert(self, verx: VectorComponent): ...

    @abc.abstractmethod
    def sort(self): ...

    @abc.abstractmethod
    def __iter__(self): ...


class TreeNode:
    def __init__(self, axis: Vertex, limit_divisions=1):
        self.__children = {}
        self.__node = Node(vertex=axis, nodes=[])
        self.__axis = axis
        self.__limit_divisions = limit_divisions

    def __hash__(self):
        return hash(self.__node)
        
    @property
    def axis(self):
        return [*self.__axis]

    @property
    def children(self):
        return self.__children

    @property
    def node(self) -> Node:
        return self.__node

    @property
    def is_parent(self):
        return len(self.children) != 0

    def insert(self, verx: VectorComponent):
        return self._insert_recursive(verx)

    def sort(self):
        return self._get_iter_child_recursive()

    def __iter__(self):
        return iter(self._get_iter_child_recursive())
        
    def _insert_recursive(self, verx: VectorComponent):
        def create_vertex(verx):
            root_axis = collections.deque()
            
            for axis, c in zip(self.axis, verx):
                x, y = axis
                d = calc_distance(x, y)
                
                if  c >= x and c <= (x + d):
                    root_axis.append((x, x + d))
                else:
                    root_axis.append((x + d, y))

            axis = list(root_axis)

            return axis

        tree = TreeNode(create_vertex(verx), self.__limit_divisions - 1)
        tree_key = hash(tree)
    
        if tree_key in self.__children:
            tree = self.__children[tree_key]
        else:
            self.__children[tree_key] = tree
        
        if self.__limit_divisions > 0:
            return tree.insert(verx)
        else:
            if not tree.node.is_collide(verx):
                raise ValueError(f"Vertex no collide: {tree.node} {verx}")
            
            tree.node.append(verx)
        
        return tree

    def _get_iter_child_recursive(self):
        def get_iter_child(root, nodes=None):
            if nodes is None:
                nodes = []

            for _, child in root.children.items():
                node = child.node
                
                if child.is_parent:
                    get_iter_child(child, nodes)
                else:
                    if len(child.node) > 0:
                        nodes.append(child.node)

            return nodes

        return get_iter_child(self, [])

## Initialize and config data

In [2]:
import sympy as sp
import numpy as np

N_COMPONENTS = 2000

syms = sp.symbols(f'x1:{N_COMPONENTS + 1}')

ALL_SYMS = syms
LIMITS_RANGE = -3, 3

def get_n_syms(_range=(-1, 1)):
    return [_range for _ in range(len(syms))]

In [3]:
import operator
import functools

x1 = syms[0]
x2 = syms[1]
# x3 = syms[2]

# eq = sum(syms)
# eq = eq.subs(x1, 1/x1**2).subs(x2, x2**2).subs(x3, x3**3)
# eq = functools.reduce(operator.mul, syms, 1)**2 / 10
eq = functools.reduce(operator.mul, syms, 1)

OBJ_FUNC = sp.lambdify([syms], eq, modules='numpy')

eq

x1*x10*x100*x1000*x1001*x1002*x1003*x1004*x1005*x1006*x1007*x1008*x1009*x101*x1010*x1011*x1012*x1013*x1014*x1015*x1016*x1017*x1018*x1019*x102*x1020*x1021*x1022*x1023*x1024*x1025*x1026*x1027*x1028*x1029*x103*x1030*x1031*x1032*x1033*x1034*x1035*x1036*x1037*x1038*x1039*x104*x1040*x1041*x1042*x1043*x1044*x1045*x1046*x1047*x1048*x1049*x105*x1050*x1051*x1052*x1053*x1054*x1055*x1056*x1057*x1058*x1059*x106*x1060*x1061*x1062*x1063*x1064*x1065*x1066*x1067*x1068*x1069*x107*x1070*x1071*x1072*x1073*x1074*x1075*x1076*x1077*x1078*x1079*x108*x1080*x1081*x1082*x1083*x1084*x1085*x1086*x1087*x1088*x1089*x109*x1090*x1091*x1092*x1093*x1094*x1095*x1096*x1097*x1098*x1099*x11*x110*x1100*x1101*x1102*x1103*x1104*x1105*x1106*x1107*x1108*x1109*x111*x1110*x1111*x1112*x1113*x1114*x1115*x1116*x1117*x1118*x1119*x112*x1120*x1121*x1122*x1123*x1124*x1125*x1126*x1127*x1128*x1129*x113*x1130*x1131*x1132*x1133*x1134*x1135*x1136*x1137*x1138*x1139*x114*x1140*x1141*x1142*x1143*x1144*x1145*x1146*x1147*x1148*x1149*x115*x1150*x1151*x1152*x1153*x1154*x1155*x1156*x1157*x1158*x1159*x116*x1160*x1161*x1162*x1163*x1164*x1165*x1166*x1167*x1168*x1169*x117*x1170*x1171*x1172*x1173*x1174*x1175*x1176*x1177*x1178*x1179*x118*x1180*x1181*x1182*x1183*x1184*x1185*x1186*x1187*x1188*x1189*x119*x1190*x1191*x1192*x1193*x1194*x1195*x1196*x1197*x1198*x1199*x12*x120*x1200*x1201*x1202*x1203*x1204*x1205*x1206*x1207*x1208*x1209*x121*x1210*x1211*x1212*x1213*x1214*x1215*x1216*x1217*x1218*x1219*x122*x1220*x1221*x1222*x1223*x1224*x1225*x1226*x1227*x1228*x1229*x123*x1230*x1231*x1232*x1233*x1234*x1235*x1236*x1237*x1238*x1239*x124*x1240*x1241*x1242*x1243*x1244*x1245*x1246*x1247*x1248*x1249*x125*x1250*x1251*x1252*x1253*x1254*x1255*x1256*x1257*x1258*x1259*x126*x1260*x1261*x1262*x1263*x1264*x1265*x1266*x1267*x1268*x1269*x127*x1270*x1271*x1272*x1273*x1274*x1275*x1276*x1277*x1278*x1279*x128*x1280*x1281*x1282*x1283*x1284*x1285*x1286*x1287*x1288*x1289*x129*x1290*x1291*x1292*x1293*x1294*x1295*x1296*x1297*x1298*x1299*x13*x130*x1300*x1301*x1302*x1303*x1304*x1305*x1306*x1307*x1308*x1309*x131*x1310*x1311*x1312*x1313*x1314*x1315*x1316*x1317*x1318*x1319*x132*x1320*x1321*x1322*x1323*x1324*x1325*x1326*x1327*x1328*x1329*x133*x1330*x1331*x1332*x1333*x1334*x1335*x1336*x1337*x1338*x1339*x134*x1340*x1341*x1342*x1343*x1344*x1345*x1346*x1347*x1348*x1349*x135*x1350*x1351*x1352*x1353*x1354*x1355*x1356*x1357*x1358*x1359*x136*x1360*x1361*x1362*x1363*x1364*x1365*x1366*x1367*x1368*x1369*x137*x1370*x1371*x1372*x1373*x1374*x1375*x1376*x1377*x1378*x1379*x138*x1380*x1381*x1382*x1383*x1384*x1385*x1386*x1387*x1388*x1389*x139*x1390*x1391*x1392*x1393*x1394*x1395*x1396*x1397*x1398*x1399*x14*x140*x1400*x1401*x1402*x1403*x1404*x1405*x1406*x1407*x1408*x1409*x141*x1410*x1411*x1412*x1413*x1414*x1415*x1416*x1417*x1418*x1419*x142*x1420*x1421*x1422*x1423*x1424*x1425*x1426*x1427*x1428*x1429*x143*x1430*x1431*x1432*x1433*x1434*x1435*x1436*x1437*x1438*x1439*x144*x1440*x1441*x1442*x1443*x1444*x1445*x1446*x1447*x1448*x1449*x145*x1450*x1451*x1452*x1453*x1454*x1455*x1456*x1457*x1458*x1459*x146*x1460*x1461*x1462*x1463*x1464*x1465*x1466*x1467*x1468*x1469*x147*x1470*x1471*x1472*x1473*x1474*x1475*x1476*x1477*x1478*x1479*x148*x1480*x1481*x1482*x1483*x1484*x1485*x1486*x1487*x1488*x1489*x149*x1490*x1491*x1492*x1493*x1494*x1495*x1496*x1497*x1498*x1499*x15*x150*x1500*x1501*x1502*x1503*x1504*x1505*x1506*x1507*x1508*x1509*x151*x1510*x1511*x1512*x1513*x1514*x1515*x1516*x1517*x1518*x1519*x152*x1520*x1521*x1522*x1523*x1524*x1525*x1526*x1527*x1528*x1529*x153*x1530*x1531*x1532*x1533*x1534*x1535*x1536*x1537*x1538*x1539*x154*x1540*x1541*x1542*x1543*x1544*x1545*x1546*x1547*x1548*x1549*x155*x1550*x1551*x1552*x1553*x1554*x1555*x1556*x1557*x1558*x1559*x156*x1560*x1561*x1562*x1563*x1564*x1565*x1566*x1567*x1568*x1569*x157*x1570*x1571*x1572*x1573*x1574*x1575*x1576*x1577*x1578*x1579*x158*x1580*x1581*x1582*x1583*x1584*x1585*x1586*x1587*x1588*x1589*x159*x1590*x1591*x1592*x1593*x1594*x1595*x1596*x1597*x1598*x1599*x16*x160*x1600*x1601*x1602*x1603*x1604*x1605*x1606*x1607*x1608*x1609*x161*x1610*x1611*x1612*x1613*x1614*x1615*x1616*x1617*x1618*x1619*x162*x1620*x1621*x1622*x1623*x1624*x1625*x1626*x1627*x1628*x1629*x163*x1630*x1631*x1632*x1633*x1634*x1635*x1636*x1637*x1638*x1639*x164*x1640*x1641*x1642*x1643*x1644*x1645*x1646*x1647*x1648*x1649*x165*x1650*x1651*x1652*x1653*x1654*x1655*x1656*x1657*x1658*x1659*x166*x1660*x1661*x1662*x1663*x1664*x1665*x1666*x1667*x1668*x1669*x167*x1670*x1671*x1672*x1673*x1674*x1675*x1676*x1677*x1678*x1679*x168*x1680*x1681*x1682*x1683*x1684*x1685*x1686*x1687*x1688*x1689*x169*x1690*x1691*x1692*x1693*x1694*x1695*x1696*x1697*x1698*x1699*x17*x170*x1700*x1701*x1702*x1703*x1704*x1705*x1706*x1707*x1708*x1709*x171*x1710*x1711*x1712*x1713*x1714*x1715*x1716*x1717*x1718*x1719*x172*x1720*x1721*x1722*x1723*x1724*x1725*x1726*x1727*x1728*x1729*x173*x1730*x1731*x1732*x1733*x1734*x1735*x1736*x1737*x1738*x1739*x174*x1740*x1741*x1742*x1743*x1744*x1745*x1746*x1747*x1748*x1749*x175*x1750*x1751*x1752*x1753*x1754*x1755*x1756*x1757*x1758*x1759*x176*x1760*x1761*x1762*x1763*x1764*x1765*x1766*x1767*x1768*x1769*x177*x1770*x1771*x1772*x1773*x1774*x1775*x1776*x1777*x1778*x1779*x178*x1780*x1781*x1782*x1783*x1784*x1785*x1786*x1787*x1788*x1789*x179*x1790*x1791*x1792*x1793*x1794*x1795*x1796*x1797*x1798*x1799*x18*x180*x1800*x1801*x1802*x1803*x1804*x1805*x1806*x1807*x1808*x1809*x181*x1810*x1811*x1812*x1813*x1814*x1815*x1816*x1817*x1818*x1819*x182*x1820*x1821*x1822*x1823*x1824*x1825*x1826*x1827*x1828*x1829*x183*x1830*x1831*x1832*x1833*x1834*x1835*x1836*x1837*x1838*x1839*x184*x1840*x1841*x1842*x1843*x1844*x1845*x1846*x1847*x1848*x1849*x185*x1850*x1851*x1852*x1853*x1854*x1855*x1856*x1857*x1858*x1859*x186*x1860*x1861*x1862*x1863*x1864*x1865*x1866*x1867*x1868*x1869*x187*x1870*x1871*x1872*x1873*x1874*x1875*x1876*x1877*x1878*x1879*x188*x1880*x1881*x1882*x1883*x1884*x1885*x1886*x1887*x1888*x1889*x189*x1890*x1891*x1892*x1893*x1894*x1895*x1896*x1897*x1898*x1899*x19*x190*x1900*x1901*x1902*x1903*x1904*x1905*x1906*x1907*x1908*x1909*x191*x1910*x1911*x1912*x1913*x1914*x1915*x1916*x1917*x1918*x1919*x192*x1920*x1921*x1922*x1923*x1924*x1925*x1926*x1927*x1928*x1929*x193*x1930*x1931*x1932*x1933*x1934*x1935*x1936*x1937*x1938*x1939*x194*x1940*x1941*x1942*x1943*x1944*x1945*x1946*x1947*x1948*x1949*x195*x1950*x1951*x1952*x1953*x1954*x1955*x1956*x1957*x1958*x1959*x196*x1960*x1961*x1962*x1963*x1964*x1965*x1966*x1967*x1968*x1969*x197*x1970*x1971*x1972*x1973*x1974*x1975*x1976*x1977*x1978*x1979*x198*x1980*x1981*x1982*x1983*x1984*x1985*x1986*x1987*x1988*x1989*x199*x1990*x1991*x1992*x1993*x1994*x1995*x1996*x1997*x1998*x1999*x2*x20*x200*x2000*x201*x202*x203*x204*x205*x206*x207*x208*x209*x21*x210*x211*x212*x213*x214*x215*x216*x217*x218*x219*x22*x220*x221*x222*x223*x224*x225*x226*x227*x228*x229*x23*x230*x231*x232*x233*x234*x235*x236*x237*x238*x239*x24*x240*x241*x242*x243*x244*x245*x246*x247*x248*x249*x25*x250*x251*x252*x253*x254*x255*x256*x257*x258*x259*x26*x260*x261*x262*x263*x264*x265*x266*x267*x268*x269*x27*x270*x271*x272*x273*x274*x275*x276*x277*x278*x279*x28*x280*x281*x282*x283*x284*x285*x286*x287*x288*x289*x29*x290*x291*x292*x293*x294*x295*x296*x297*x298*x299*x3*x30*x300*x301*x302*x303*x304*x305*x306*x307*x308*x309*x31*x310*x311*x312*x313*x314*x315*x316*x317*x318*x319*x32*x320*x321*x322*x323*x324*x325*x326*x327*x328*x329*x33*x330*x331*x332*x333*x334*x335*x336*x337*x338*x339*x34*x340*x341*x342*x343*x344*x345*x346*x347*x348*x349*x35*x350*x351*x352*x353*x354*x355*x356*x357*x358*x359*x36*x360*x361*x362*x363*x364*x365*x366*x367*x368*x369*x37*x370*x371*x372*x373*x374*x375*x376*x377*x378*x379*x38*x380*x381*x382*x383*x384*x385*x386*x387*x388*x389*x39*x390*x391*x392*x393*x394*x395*x396*x397*x398*x399*x4*x40*x400*x401*x402*x403*x404*x405*x406*x407*x408*x409*x41*x410*x411*x412*x413*x414*x415*x416*x417*x418*x419*x42*x420*x421*x422*x423*x424*x425*x426*x427*x428*x429*x43*x430*x431*x432*x433*x434*x435*x436*x437*x438*x439*x44*x440*x441*x442*x443*x444*x445*x446*x447*x448*x449*x45*x450*x451*x452*x453*x454*x455*x456*x457*x458*x459*x46*x460*x461*x462*x463*x464*x465*x466*x467*x468*x469*x47*x470*x471*x472*x473*x474*x475*x476*x477*x478*x479*x48*x480*x481*x482*x483*x484*x485*x486*x487*x488*x489*x49*x490*x491*x492*x493*x494*x495*x496*x497*x498*x499*x5*x50*x500*x501*x502*x503*x504*x505*x506*x507*x508*x509*x51*x510*x511*x512*x513*x514*x515*x516*x517*x518*x519*x52*x520*x521*x522*x523*x524*x525*x526*x527*x528*x529*x53*x530*x531*x532*x533*x534*x535*x536*x537*x538*x539*x54*x540*x541*x542*x543*x544*x545*x546*x547*x548*x549*x55*x550*x551*x552*x553*x554*x555*x556*x557*x558*x559*x56*x560*x561*x562*x563*x564*x565*x566*x567*x568*x569*x57*x570*x571*x572*x573*x574*x575*x576*x577*x578*x579*x58*x580*x581*x582*x583*x584*x585*x586*x587*x588*x589*x59*x590*x591*x592*x593*x594*x595*x596*x597*x598*x599*x6*x60*x600*x601*x602*x603*x604*x605*x606*x607*x608*x609*x61*x610*x611*x612*x613*x614*x615*x616*x617*x618*x619*x62*x620*x621*x622*x623*x624*x625*x626*x627*x628*x629*x63*x630*x631*x632*x633*x634*x635*x636*x637*x638*x639*x64*x640*x641*x642*x643*x644*x645*x646*x647*x648*x649*x65*x650*x651*x652*x653*x654*x655*x656*x657*x658*x659*x66*x660*x661*x662*x663*x664*x665*x666*x667*x668*x669*x67*x670*x671*x672*x673*x674*x675*x676*x677*x678*x679*x68*x680*x681*x682*x683*x684*x685*x686*x687*x688*x689*x69*x690*x691*x692*x693*x694*x695*x696*x697*x698*x699*x7*x70*x700*x701*x702*x703*x704*x705*x706*x707*x708*x709*x71*x710*x711*x712*x713*x714*x715*x716*x717*x718*x719*x72*x720*x721*x722*x723*x724*x725*x726*x727*x728*x729*x73*x730*x731*x732*x733*x734*x735*x736*x737*x738*x739*x74*x740*x741*x742*x743*x744*x745*x746*x747*x748*x749*x75*x750*x751*x752*x753*x754*x755*x756*x757*x758*x759*x76*x760*x761*x762*x763*x764*x765*x766*x767*x768*x769*x77*x770*x771*x772*x773*x774*x775*x776*x777*x778*x779*x78*x780*x781*x782*x783*x784*x785*x786*x787*x788*x789*x79*x790*x791*x792*x793*x794*x795*x796*x797*x798*x799*x8*x80*x800*x801*x802*x803*x804*x805*x806*x807*x808*x809*x81*x810*x811*x812*x813*x814*x815*x816*x817*x818*x819*x82*x820*x821*x822*x823*x824*x825*x826*x827*x828*x829*x83*x830*x831*x832*x833*x834*x835*x836*x837*x838*x839*x84*x840*x841*x842*x843*x844*x845*x846*x847*x848*x849*x85*x850*x851*x852*x853*x854*x855*x856*x857*x858*x859*x86*x860*x861*x862*x863*x864*x865*x866*x867*x868*x869*x87*x870*x871*x872*x873*x874*x875*x876*x877*x878*x879*x88*x880*x881*x882*x883*x884*x885*x886*x887*x888*x889*x89*x890*x891*x892*x893*x894*x895*x896*x897*x898*x899*x9*x90*x900*x901*x902*x903*x904*x905*x906*x907*x908*x909*x91*x910*x911*x912*x913*x914*x915*x916*x917*x918*x919*x92*x920*x921*x922*x923*x924*x925*x926*x927*x928*x929*x93*x930*x931*x932*x933*x934*x935*x936*x937*x938*x939*x94*x940*x941*x942*x943*x944*x945*x946*x947*x948*x949*x95*x950*x951*x952*x953*x954*x955*x956*x957*x958*x959*x96*x960*x961*x962*x963*x964*x965*x966*x967*x968*x969*x97*x970*x971*x972*x973*x974*x975*x976*x977*x978*x979*x98*x980*x981*x982*x983*x984*x985*x986*x987*x988*x989*x99*x990*x991*x992*x993*x994*x995*x996*x997*x998*x999

## Execution

In [4]:
import collections
import functools
import itertools

import pandas as pd

def tree_search_algorithm(f, axis, n_it=10, n_p=5, n_limit=0):
    tree = TreeNode(axis)

    all_it = collections.deque()
    all_it_route = collections.deque()

    for it in range(n_it):
        local_min_point = collections.deque()

        for _ in range(n_p):
            data = [np.random.uniform(*_) for _ in tree.axis]
            value = f(data)

            tree.insert(VectorNode(data, value))

        for container in tree.sort():
            min_node = min(container)

            local_min_point.append(
                NodeValue(container.vertex, min_node)
            )

        if len(local_min_point) <= 0:
            continue

        local_min_node = min(local_min_point)

        all_it.append(list(min(local_min_point).node))
        all_it_route.append(local_min_node.vertex)

        tree = TreeNode(local_min_node.vertex, 2)

    return all_it, all_it_route


all_it, all_it_route = tree_search_algorithm(
    OBJ_FUNC, [(-3, 3) for _ in range(len(syms))], 10, 30, 2
)

In [5]:
pd.DataFrame(all_it_route)

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,"(1.5, 3)","(0.0, 1.5)","(-3, -1.5)","(-1.5, 0.0)","(-3, -1.5)","(-3, -1.5)","(0.0, 1.5)","(1.5, 3)","(0.0, 1.5)","(1.5, 3)",...,"(1.5, 3)","(-1.5, 0.0)","(-3, -1.5)","(0.0, 1.5)","(-1.5, 0.0)","(0.0, 1.5)","(1.5, 3)","(1.5, 3)","(-3, -1.5)","(1.5, 3)"
1,"(2.25, 2.4375)","(0.375, 0.5625)","(-2.8125, -2.625)","(-1.5, -1.3125)","(-2.625, -2.4375)","(-2.8125, -2.625)","(0.0, 0.1875)","(2.625, 2.8125)","(0.75, 0.9375)","(2.4375, 2.625)",...,"(2.8125, 3)","(-1.3125, -1.125)","(-1.6875, -1.5)","(1.3125, 1.5)","(-0.9375, -0.75)","(0.1875, 0.375)","(2.8125, 3)","(1.5, 1.6875)","(-2.8125, -2.625)","(2.625, 2.8125)"
2,"(2.4140625, 2.4375)","(0.46875, 0.4921875)","(-2.7890625, -2.765625)","(-1.359375, -1.3359375)","(-2.578125, -2.5546875)","(-2.7890625, -2.765625)","(0.140625, 0.1640625)","(2.71875, 2.7421875)","(0.75, 0.7734375)","(2.6015625, 2.625)",...,"(2.8828125, 2.90625)","(-1.265625, -1.2421875)","(-1.5703125, -1.546875)","(1.453125, 1.4765625)","(-0.8203125, -0.796875)","(0.2109375, 0.234375)","(2.90625, 2.9296875)","(1.6171875, 1.640625)","(-2.7421875, -2.71875)","(2.6484375, 2.671875)"
3,"(2.4287109375, 2.431640625)","(0.48046875, 0.4833984375)","(-2.77734375, -2.7744140625)","(-1.3388671875, -1.3359375)","(-2.572265625, -2.5693359375)","(-2.7802734375, -2.77734375)","(0.140625, 0.1435546875)","(2.73046875, 2.7333984375)","(0.7529296875, 0.755859375)","(2.6044921875, 2.607421875)",...,"(2.888671875, 2.8916015625)","(-1.25390625, -1.2509765625)","(-1.55859375, -1.5556640625)","(1.4677734375, 1.470703125)","(-0.814453125, -0.8115234375)","(0.2109375, 0.2138671875)","(2.9208984375, 2.923828125)","(1.6318359375, 1.634765625)","(-2.7392578125, -2.736328125)","(2.6630859375, 2.666015625)"
4,"(2.4305419921875, 2.430908203125)","(0.482666015625, 0.4830322265625)","(-2.776611328125, -2.7762451171875)","(-1.336669921875, -1.3363037109375)","(-2.5718994140625, -2.571533203125)","(-2.7791748046875, -2.77880859375)","(0.1424560546875, 0.142822265625)","(2.7322998046875, 2.732666015625)","(0.7540283203125, 0.75439453125)","(2.6048583984375, 2.605224609375)",...,"(2.8890380859375, 2.889404296875)","(-1.25244140625, -1.2520751953125)","(-1.5574951171875, -1.55712890625)","(1.4688720703125, 1.46923828125)","(-0.814453125, -0.8140869140625)","(0.2109375, 0.2113037109375)","(2.9227294921875, 2.923095703125)","(1.6343994140625, 1.634765625)","(-2.73779296875, -2.7374267578125)","(2.665283203125, 2.6656494140625)"
5,"(2.430633544921875, 2.4306793212890625)","(0.482757568359375, 0.4828033447265625)","(-2.7763824462890625, -2.776336669921875)","(-1.33648681640625, -1.3364410400390625)","(-2.571624755859375, -2.5715789794921875)","(-2.7789459228515625, -2.778900146484375)","(0.1427764892578125, 0.142822265625)","(2.732574462890625, 2.7326202392578125)","(0.7542572021484375, 0.754302978515625)","(2.6048583984375, 2.6049041748046875)",...,"(2.8890838623046875, 2.889129638671875)","(-1.25225830078125, -1.2522125244140625)","(-1.557220458984375, -1.5571746826171875)","(1.4690093994140625, 1.46905517578125)","(-0.814178466796875, -0.8141326904296875)","(0.2112579345703125, 0.2113037109375)","(2.923004150390625, 2.9230499267578125)","(1.634490966796875, 1.6345367431640625)","(-2.7377471923828125, -2.737701416015625)","(2.66546630859375, 2.6655120849609375)"
6,"(2.4306392669677734, 2.430644989013672)","(0.4827690124511719, 0.4827747344970703)","(-2.776365280151367, -2.7763595581054688)","(-1.3364696502685547, -1.3364639282226562)","(-2.5716190338134766, -2.571613311767578)","(-2.7789230346679688, -2.7789173126220703)","(0.14279937744140625, 0.1428050994873047)","(2.732585906982422, 2.7325916290283203)","(0.7542915344238281, 0.7542972564697266)","(2.6048755645751953, 2.6048812866210938)",...,"(2.8890953063964844, 2.889101028442383)","(-1.2522468566894531, -1.2522411346435547)","(-1.557180404663086, -1.5571746826171875)","(1.4690322875976562, 1.4690380096435547)","(-0.8141498565673828, -0.8141441345214844)","(0.21126365661621094, 0.21126937866210938)","(2.9230098724365234, 2.923015594482422)","(1.6344966888427734, 1.6345024108886719)","(-2.7377185821533203, -2.737712860107422)","(2.6654834747314453, 2.6654891967773438)"
7,"(2.4306442737579346, 2.430644989013672)","(0.4827690124511719, 0.4827697277069092)","(-2.7763631343841553, -2.776362419128418)","(-1.3364675045013428, -1.3364667892456055)","(-2.5716140270233154, -2.571613311767578)","(-2.778921604156494, -2.778920888900757)","(0.14280295372009277, 0.14280366897583008)","(2.732590913772583, 2.7325916290283203)","(0.7542943954467773, 0.7542951107025146)","(2.604879140853882, 2.604879856109619)",...,"(2.889099597930908, 2.8891003131866455)","(-1.2522425651550293, -1.252241849899292)","(-1.557178258895874, -1.5571775436401367)","(1.4690330028533936, 1.4690337181091309)","(-0.8141498565673828, -0.8141491413116455)","(0.21126437187194824, 0.21126508712768555)","(2.9230120182037354, 2.9230127334594727)","(1.6344995498657227, 1.63450026512146)","(-2.737713575363159, -2.737712860107422)","(2.6654884815216064, 2.6654891967773438)"
8,"(2.4306448996067047, 2.430644989013672)","(0.4827690124511719, 0.48276910185813904)","(-2.776362866163254, -2.7763627767562866)","(-1.3364669680595398, -1.3364668786525726)","(-2.5716134905815125, -2.5716134011745453)","(-2.77892142534256, -2.7789213359355927)","(0.1428034007549286, 0.14280349016189575)","(2.73259100317955, 2.7325910925865173)","(0.7542950212955475, 0.7542951107025146)","(2.6048795878887177, 2.604879677295685)",...,"(2.889099597930908, 2.8890996873378754)","(-1.2522420287132263, -1.2522419393062592)","(-1.557177722454071, -1.5571776330471039)","(1.4690333604812622, 1.4690334498882294)","(-0.8141497671604156, -0.8141496777534485)","(0.21126455068588257, 0.21126464009284973)","(2.9230120182037354, 2.9230121076107025)","(1.6344996392726898, 1.634499728679657)","(-2.737712949514389, -2.737712860107422)","(2.6654884815216064, 2.6654885709285736)"
9,"(2.4306449107825756, 2.4306449219584465)","(0.48276902362704277, 0.48276903480291367)","(-2.77636282145977, -2.7763628102838993)","(-1.336466956883669, -1.336466945707798)","(-2.5716134682297707, -2.5716134570538998)","(-2.778921402990818, -2.778921391814947)","(0.14280343428254128, 0.14280344545841217)","(2.732591014355421, 2.732591025531292)","(0.7542950548231602, 0.7542950659990311)","(2.604879643768072, 2.604879654943943)",...,"(2.889099609106779, 2.88909962028265)","(-1.2522419728338718, -1.252241961658001)","(-1.5571777001023293, -1.5571776889264584)","(1.4690333604812622, 1.469033371657133)","(-0.814149733632803, -0.8141497224569321)","(0.21126462891697884, 0.21126464009284973)","(2.9230120182037354, 2.9230120293796062)","(1.6344996392726898, 1.6344996504485607)","(-2.737712949514389, -2.737712938338518)","(2.665488548576832, 2.6654885597527027)"

In [6]:
pd.DataFrame(all_it)

,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
0,1.761127,1.035069,-1.919538,-0.664001,-2.346025,-2.420592,0.044137,2.473633,0.362794,2.418150,...,-0.228163,-2.242567,1.048373,-0.874006,0.844792,2.818769,1.599051,-2.946239,2.625714,-7.683977e+129
1,2.432580,0.481036,-2.630333,-1.495477,-2.570938,-2.802173,0.065148,2.658010,0.900027,2.503656,...,-1.201366,-1.578178,1.429485,-0.825123,0.316609,2.910545,1.507782,-2.625371,2.765773,-1.072428e+136
2,2.429496,0.487830,-2.771390,-1.336970,-2.562097,-2.767464,0.151728,2.737654,0.773284,2.608399,...,-1.255545,-1.549476,1.475934,-0.799030,0.219888,2.912760,1.626947,-2.724020,2.649595,-8.151357e+143
3,2.429934,0.482255,-2.774644,-1.338531,-2.571484,-2.777447,0.142812,2.731711,0.754113,2.607202,...,-1.252319,-1.556225,1.468453,-0.811678,0.210948,2.921696,1.633392,-2.738563,2.664506,-4.415111e+145
4,2.430558,0.482838,-2.776417,-1.336633,-2.571671,-2.779006,0.142534,2.732399,0.754286,2.604939,...,-1.252096,-1.557408,1.469101,-0.814194,0.211291,2.922768,1.634536,-2.737615,2.665576,-1.575627e+146
5,2.430648,0.482758,-2.776379,-1.336479,-2.571583,-2.778903,0.142811,2.732595,0.754275,2.604876,...,-1.252248,-1.557182,1.469053,-0.814173,0.211268,2.923012,1.634503,-2.737731,2.665469,-1.641105e+146
6,2.430642,0.482772,-2.776364,-1.336469,-2.571615,-2.778921,0.142803,2.732586,0.754292,2.604880,...,-1.252242,-1.557178,1.469036,-0.814146,0.211267,2.923012,1.634498,-2.737716,2.665488,-1.636347e+146
7,2.430645,0.482769,-2.776362,-1.336467,-2.571614,-2.778921,0.142803,2.732591,0.754295,2.604880,...,-1.252242,-1.557178,1.469034,-0.814150,0.211264,2.923012,1.634500,-2.737713,2.665489,-1.636098e+146
8,2.430645,0.482769,-2.776363,-1.336467,-2.571613,-2.778921,0.142803,2.732591,0.754295,2.604880,...,-1.252242,-1.557178,1.469033,-0.814150,0.211265,2.923012,1.634500,-2.737713,2.665489,-1.636349e+146
9,2.430645,0.482769,-2.776363,-1.336467,-2.571613,-2.778921,0.142803,2.732591,0.754295,2.604880,...,-1.252242,-1.557178,1.469033,-0.814150,0.211265,2.923012,1.634500,-2.737713,2.665489,-1.636376e+146